name: portfolio
description: "portfolio project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/field/
    - assets/images/contact/
    - assets/images/project/simple_discord/
    - assets/images/project/server_engine/
    - assets/images/project/three_kingdoms/
    - assets/images/project/pixel_universe/
    - assets/images/project/pin_engine/
    - assets/images/project/rechargeable_fireworks/
    - assets/images/project/better_spyglass/
    - assets/images/project/lethal_scanner/
    - assets/images/project/server_engine_web/
    - assets/images/project/league_archive/
    - assets/images/project/celestial_tracker/
    - assets/images/project/server_lister/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMonoNL-Light.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMonoNL-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMonoNL-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMonoNL-ExtraBold.ttf
          weight: 800
